<script setup lang="ts">
import { SliceSimulator } from "@slicemachine/adapter-nuxt/simulator";
import { components } from "~/slices";
</script>

<template>
  <SliceSimulator v-slot="{ slices }" background="#030712">
    <SliceZone :slices="slices" :components="components" />
  </SliceSimulator>
</template>

<!-- the slice machine’s development environment can be thought of as a craftsman’s workshop, a place where we can create and shape data models while benefiting from features like version control, component previews, and autogenerated markup. within this tool, we can create three types of data models: first, page types, these represent pages, blog posts, landing pages, or anything that has a url on our website. second, custom types, these are more abstract content collections, such as taxonomy or offer collections, navigation documents, or settings documents, which don’t necessarily map to a specific page. and finally, we have slices, which are sections that we have on a single page -->

<!-- the difference between reusable types and single types is that reusable types allow us to create multiple instances of a document within prismic, while single types are meant for content that exists only once across the site. in our case, since we only want a sitewide settings document, we’ll use a single type, as we only need one instance of this document in our content platform. -->

<!-- tabs in prismic are simply a way to organize content for content writers, making it easier to manage and navigate different sections of a document. this feature is especially useful for keeping complex content structures clear and well-organized. -->
